# Generated by Django 4.2 on 2023-05-02 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_person_delete_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Person',
        ),
    ]
